name: Build Windows

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      binary:
        required: true
        type: string


jobs:
  github-releases:
    name: windows
    env:
      platform: windows-x86_64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          cargo build --release --target x86_64-pc-windows-msvc

      - name: Set file name
        id: set_file_name
        shell: bash
        run: |
          echo "file_name=${{ inputs.binary }}_${{ inputs.tag }}_${{ env.platform }}" >> "$GITHUB_OUTPUT"

      - name: Prepare package
        shell: bash
        run: |
          cp target/x86_64-pc-windows-msvc/release/${{ inputs.binary }}.exe ${{ steps.set_file_name.outputs.file_name }}.exe

      - name: Upload binaries to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.platform }}
          path: ${{ steps.set_file_name.outputs.file_name }}.exe
          retention-days: 1
